In [ ]:
# %pip install pandas seaborn

In [1]:
import pandas as pd
import seaborn as sns

# Pandas and DataFrames

Often, we have tables of data--collections of named columns arranged in rows.  The **Pandas** package gives us a **DataFrame()** class that lets us index these columns the same way as with dicts, while still getting the benefit of Numpy arrays, meaning we can still write vectorized code.  

Because Pandas makes it easy to do many analysis steps in a single line, getting used to working with Pandas often means getting used to **Method Chaining**: calling a series of methods all at once.

## Today's Dataset: Mental Rotation Psychology Experiment

![Mental Rotation Task Example](http://mercercognitivepsychology.pbworks.com/f/1353970952/mental-rotation-image.gif)

## Setup: Dataset

Please open the file “MentalRotation.csv” found at **"data/MentalRotation.csv"** (hint: `pd.read_csv()`) and use it to answer the following questions about the results of the Mental Rotation psychology experiment.

In [2]:
df = pd.read_csv('data/MentalRotation.csv')
df.head()

   Subject  Trial  Angle  Matching Response  Time  Correct  Age Sex
0       49      1      0         0        n  3107        1   32   M
1       49      2    150         0        n  2930        1   32   M
2       49      3    150         1        b  1874        1   32   M
3       49      4    100         1        b  3793        1   32   M
4       49      5     50         1        b  2184        1   32   M

## Examining the Dataset

| With Slicing | With Method | With Function |
| :-- | :-- | :-- |
| `df[:5]` | `df.head()` |   |
| `df[-5:]` | `df.tail()` |  |
|  | `df.sample(5)` |   | 
|  | `df.info()` |   |
|  | `df.describe()` |   |
|  | `df.shape[0]` | `len(df)` |

**Exercise**: Print the first 5 lines of the dataset:

In [ ]:
df[:5]

   Subject  Trial  Angle  Matching Response  Time  Correct  Age Sex
0       49      1      0         0        n  3107        1   32   M
1       49      2    150         0        n  2930        1   32   M
2       49      3    150         1        b  1874        1   32   M
3       49      4    100         1        b  3793        1   32   M
4       49      5     50         1        b  2184        1   32   M

**Exercise**: Look at the last 5 lines of the dataset

In [ ]:
df[-5:]

      Subject  Trial  Angle  Matching Response  Time  Correct  Age Sex
5066       33     92    150         1        b  2095        1   20   F
5067       33     93    150         0        n  2125        1   20   F
5068       33     94     50         0        n  1226        1   20   F
5069       33     95    100         1        b  2783        1   20   F
5070       33     96      0         0        n  1017        1   20   F

**Exercise**: Check 3 random lines in the dataset.

In [ ]:
df.sample(3)

      Subject  Trial  Angle  Matching Response  Time  Correct  Age Sex
907        48     55    150         1        n  2147        0   18   F
1996       21     20     50         1        n  2363        0   33   M
2088       53     19     50         0        n  4340        1   18   F

**Exercise**: How Many Total Trials (rows) are in the study?

In [ ]:
len(df)

5071

## Calculating Values on Columns

| Method | Example |
| :-- | :-- |
| `.max()` | `df['Height'].max()` |
| `.min()` | `df['Weight'].min()` |
| `.mean()` | `df['Time'].mean()` |
| `.median()` | `df['Speed'].median()` |
| `.value_counts()` | `df['Kind'].value_counts()` |

**Exercise**: What is the maximum number of trials that one subject performed?

In [4]:
df['Trial'].max()

np.int64(96)

**Exercise**: What was the median reaction time across all subjects?

In [5]:
df['Time'].median()

np.float64(2402.0)

**Exercise**: What was the average accuracy rate (i.e. proportion of correct trials) across all subjects?

In [6]:
df['Correct'].mean()

np.float64(0.9045553145336226)

**Exercise**: How many trials were shown at each Angle?

In [7]:
df['Angle'].value_counts()

Angle
50     1280
0      1274
100    1261
150    1256
Name: count, dtype: int64

**Exercise**: How many trials were answered correctly and incorrectly, for each angle? (hint: `df[['A', 'B']]`)

In [8]:
df[['Angle', 'Correct']].value_counts()

Angle  Correct
0      1          1216
50     1          1198
100    1          1121
150    1          1052
       0           204
100    0           140
50     0            82
0      0            58
Name: count, dtype: int64

### Making New Columns

Columns can be appended to Pandas DataFrames in different ways:

| Code | Description |
| :-- | :-- |
| `df['NewCol'] = df['OldCol'] * 10` |  Append a column, modifying that dataframe |
| `df2 = df.assign(NewCol = df['OldCol'] * 10)` | Make a new dataframe with an additional column on it |

**Exercise**: Make a "TimeSecs" column by converting the Time column to seconds by dividing it by 1000.

In [9]:
df['TimeSecs'] = df['Time'] / 1000
df[:5]

,Subject,Trial,Angle,Matching,Response,Time,Correct,Age,Sex,IsCorrect,TimeSecs
0,49,1,0,0,n,3107,1,32,M,True,3.107
1,49,2,150,0,n,2930,1,32,M,True,2.930
2,49,3,150,1,b,1874,1,32,M,True,1.874
3,49,4,100,1,b,3793,1,32,M,True,3.793
4,49,5,50,1,b,2184,1,32,M,True,2.184

**Exercises**: Make an "IsCorrect" column by converting the "Correct" column to *bool* (True/False) values

In [10]:
df['IsCorrect'] = df['Correct'] == 1
df[:5]

,Subject,Trial,Angle,Matching,Response,Time,Correct,Age,Sex,IsCorrect,TimeSecs
0,49,1,0,0,n,3107,1,32,M,True,3.107
1,49,2,150,0,n,2930,1,32,M,True,2.930
2,49,3,150,1,b,1874,1,32,M,True,1.874
3,49,4,100,1,b,3793,1,32,M,True,3.793
4,49,5,50,1,b,2184,1,32,M,True,2.184

**Exercise**: Overwrite the "Response" column to one in which all the string values are upper-case (hint: df["Column"].str.upper()):

In [15]:
df["Response"] = df.Response.str.upper()
df

,Subject,Trial,Angle,Matching,Response,Time,Correct,Age,Sex,IsCorrect,TimeSecs
0,49,1,0,0,N,3107,1,32,M,True,3.107
1,49,2,150,0,N,2930,1,32,M,True,2.930
2,49,3,150,1,B,1874,1,32,M,True,1.874
3,49,4,100,1,B,3793,1,32,M,True,3.793
4,49,5,50,1,B,2184,1,32,M,True,2.184
...,...,...,...,...,...,...,...,...,...,...,...
5066,33,92,150,1,B,2095,1,20,F,True,2.095
5067,33,93,150,0,N,2125,1,20,F,True,2.125
5068,33,94,50,0,N,1226,1,20,F,True,1.226
5069,33,95,100,1,B,2783,1,20,F,True,2.783
5070,33,96,0,0,N,1017,1,20,F,True,1.017

### Logical Indexing

Logical Masking works just as it does in Numpy, making for a concise way to search for data.

| Code | Description |
| :-- | :-- |
| `df[df['Time'] > 3]` | Get only the rows, for which the "Time" column is greater than 3 |
| `len(df[df['Time'] > 3])` | Count how many rows there are, for which the "Time" column is greater than 3 |

**Example**: How many trials used an angle of 150?

In [ ]:
len(df[df['Angle'] == 150])

1256

**Exercise**: How many trials had response times longer than 3 seconds?

In [ ]:
len(df[df['TimeSecs'] > 3])

1723

**Exercise**: What was the accuracy of subject 9?

In [ ]:
df[df['Subject'] == 9].Correct.mean()

0.9578947368421052

**Exercise**: What was the average response time of subject 32?

In [ ]:
df[df['Subject'] == 32].Time.median()

2398.0

**Exercise**: What was the average response time for subject 12 on trials with an Angle of 50? (Hint: `(A) & (B)`)

In [ ]:
df[(df['Subject'] == 12) & (df['Angle'] == 50)].Time.median()

1591.5

**Exercise**: Was there an overall difference in response accuracy between matching and non-matching trials?

**Exercise**: Is there a response time difference between matching and nonmatching
trials?

## Group By

Doing the same analysis for different groups of data is enabled with the `.groupby()` method.  This does the analysis **for each** same-valued group in a column.

| Code | Description |
| :-- | :-- |
| `df.groupby('Age').Time.mean()` | For each age in the "Age" column, calculate the mean "Time" value. |

**Example:** What was the response accuracy for matching and non-matching trials?

In [ ]:
df.groupby('Matching').IsCorrect.mean()

Matching
0    0.909163
1    0.899961
Name: IsCorrect, dtype: float64

Example: What was the response accuracy for Each Angle?

In [18]:
df.groupby('Angle').IsCorrect.mean()

Angle
0      0.954474
50     0.935937
100    0.888977
150    0.837580
Name: IsCorrect, dtype: float64

What was the response accuracy for each Angle and Matching/Nonmatching value?

In [20]:
df.groupby(['Angle', 'Matching']).IsCorrect.mean()

Angle  Matching
0      0           0.924647
       1           0.984301
50     0           0.949843
       1           0.922118
100    0           0.897764
       1           0.880315
150    0           0.863708
       1           0.811200
Name: IsCorrect, dtype: float64

What was the average response time for each Angle and Matching/Nonmatching value?

In [21]:
df.groupby(['Angle', 'Matching']).Time.mean()

Angle  Matching
0      0           2350.321821
       1           1554.967033
50     0           2616.078370
       1           2508.193146
100    0           3169.239617
       1           3107.848819
150    0           3244.274168
       1           3332.628800
Name: Time, dtype: float64

What was the average response time for each Angle and Matching/Nonmatching value, for each subject?

In [22]:
df.groupby(['Subject', 'Angle', 'Matching']).IsCorrect.mean()

Subject  Angle  Matching
1        0      0           1.000000
                1           1.000000
         50     0           0.916667
                1           0.750000
         100    0           0.916667
                              ...
54       50     1           1.000000
         100    0           0.833333
                1           0.909091
         150    0           0.818182
                1           0.916667
Name: IsCorrect, Length: 432, dtype: float64

### Plotting with Pandas

| Syntax |
| :-- |
| `df['Column'].plot(kind='hist')` |
| `df['Column'].plot.hist()` |
| `df.hist('Column', by='Group')` |
| `df.plot(x='Age', y='Height', kind='scatter')` |
| `df.plot.scatter(x='Age', y='Height')` |

### Exercises

Make a plot for each analysis question.  Note that sometimes you'll need to transform the data into simpler values (e.g. pre-averaging the data, or doing a group-by analysis first) before plotting.

**Exercise**: Plot the response time distribution as a histogram.

**Exercise**: Plot the average response time for each stimulus category (matching and non-matching)

**Exercise**: Is there a correlation between Angle of mental rotation and response time?  Visualize the relationship using a scatter plot

**Exercise**: Is there a relationship between subject age and average response time?   Visualize the relationship using a box plot

**Exercise**: Did participants get faster or slower as they did more trials? Visualize the relationship using a scatter plot

**Exercise**: Plot the response time distribution, with a seperate subplot for each subject.