# Pandas DataFrames

## Setup

### Import Libraries

In [4]:
import pandas as pd

## What is a DataFrame?

A DataFrame, simply put, is a **Table** of data.  It is a structure that contains multiple rows, each row containing the same labelled collection of data types.  A **DataFrame** is a table with named rows (called the "index"). For example, a DataFrame might look like this:

| (index) | Name | Age | Height | LikesIceCream |
| :---: | :--: | :--: | :--: | :--: |
| 0     | "Nick" | 22 | 3.4 | True |
| 1     | "Jenn" | 55 | 1.2 | True |
| 2     | "Joe"  | 25 | 2.2 | True |

Because each row contains the same data, DataFrames can also be thought of as a collection of same-length columns!

**Pandas** is a Python package that has a DataFrame class.  Using either the **DataFrame** class constructor or one of Pandas' many **read_()** functions, you can make your own DataFrame from a variety of sources.  

#### **Exercise**

Below are four (yes, four!) different ways to turn code from built-in Python types into a pandas Dataframe. Take a look at each example below, and then try one of them out afterward.

**Example**: Create a DataFrame from a List of Dicts

In [ ]:
friends = [
    {'Name': "Nick", "Age": 31, "Height": 2.9, "Weight": 20},
    {'Name': "Jenn", "Age": 55, "Height": 1.2},
    {"Name": "Joe", "Height": 1.2, "Age": 25, },
]
df = pd.DataFrame(friends)
df

,Name,Age,Height,Weight
0,Nick,31,2.9,20.0
1,Jenn,55,1.2,NaN
2,Joe,25,1.2,NaN

**Example**: Create a DataFrame from a Dict of Lists

In [ ]:
df = pd.DataFrame({
    'Name': ['Nick', 'Jenn', 'Joe'], 
    'Age': [31, 55, 25], 
    'Height': [2.9, 1.2, 1.2],
})
df

,Name,Age,Height
0,Nick,31,2.9
1,Jenn,55,1.2
2,Joe,25,1.2

**Example**: Create a DataFrame from a Dict of Lists (and a list of column labels)

In [ ]:
friends = [
    ['Nick', 31, 2.9],
    ['Jenn', 55, 1.2],
    ['Joe',  25, 1.2],
]
pd.DataFrame(friends, columns=["Name", "Age", "Height"])

,Name,Age,Height
0,Nick,31,2.9
1,Jenn,55,1.2
2,Joe,25,1.2


**Example**: Create a DataFrame, starting with an empty DataFrame and appending columns one at a time.

In [5]:
df = pd.DataFrame()
df['Name'] = ['Nick', 'Jenn', 'Joe']
df['Age'] = [31, 55, 25]
df['Height'] = [2.9, 1.2, 1.2]
df

   Name  Age  Height
0  Nick   31     2.9
1  Jenn   55     1.2
2   Joe   25     1.2

**Exercise**: Please use recreate the table below as a Dataframe, by using one of the approaches shown in the previous examples:

| Year | Product | Cost |
| :--: | :----:  | :--: |
| 2015 | Apples  | 0.35 |
| 2016 | Apples  | 0.45 |
| 2015 | Bananas | 0.75 |
| 2016 | Bananas | 1.10 |

In [11]:
df = pd.DataFrame()
df['Year'] = [2015, 2016, 2015, 2016]
df['Product'] = ['Apples', 'Apples', 'Bananas', 'Bananas']
df

   Year  Product
0  2015   Apples
1  2016   Apples
2  2015  Bananas
3  2016  Bananas

## Reading Data from Files into a DataFrame

| File Format | File Extension | `read_xxx()` function | Dataframe Write Method | 
| :--:  | :--: | :--: | :--: |
| Comma-Seperated Values      | .csv           | `pd.read_csv()` | `df.to_csv()` |
| Tab-seperated Values       | .tsv, .tabular, .csv | `pd.read_csv(sep='\t')`, `pd.read_table()` | `df.to_csv(sep='\t')` `df.to_table()` |
| Excel Spreadsheet           |  .xls | `pd.read_excel()`                    | `df.to_excel()`  |
| Excel Spreadsheet 2010      | .xlsx | `pd.read_excel(engine='openpyxl')`   | `df.to_excel(engine='openpyxl')` |
| JSON                        | .json | `pd.read_json()`                     | `df.to_json()` |
| Tables in a Web Page (HTML) | .html | `pd.read_html()[0]`                  | `df.to_html()` |
| HDF5 | .hdf5, .h5, | `pd.read_hdf()` |  `df.to_hdf()` |

#### Understanding Different File Formats

Run the code below to download the Titanic passengers dataset, and transform it into different file formats

*Note*: Yep, that's right, you can supply a web url and pandas reads it like a normal file!

#### **Exercises**

In [12]:
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'
df = pd.read_csv(url)
df[:5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Now run the code below to save the file to a comma-seperated file using the `DataFrame.to_csv()` method.

In [18]:
df.to_csv("titanic2001.csv", index=False, sep='.', decimal=',')

**Exercise**: Use a text editor to examine the file that was saved on the computer. How is the file structured?

**Exercise**: Now read the file back into Python using the `pd.read_csv()` function:

In [21]:
pd.read_csv('titanic2001.csv', sep='.', decimal=',')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

**JSON**

**Exercise**: Save the dataframe to a JSON file using the `df.to_json()` method. Make sure to use the correct extension in the filename.

**Exercise**: Read the JSON file into Pandas again, using the `pd.read_json()` method.

**HTML**

**Exercise**: Save the dataframe to a HTML file, using the `df.to_html()` method.

**Exercise**: Read the HTML file into Pandas again, using the `pd.read_html()` function.

*Note*: Because HTML files can contain multiple dataframes, you'll get a `list` of dataframes instead of just one.  Just add `[0]` onto the end of the line to get the first dataframe, and it will look the same as before.

**Exercise**: Try opening the file with a text editor, then with a web browser (e.g. Chrome, Firefox, etc).  What does the file look like in each case?
In text editor:

**Exercise**: Save the dataframe to an Excel file.  `DataFrame.to_excel(engine='openpyxl')`
Note: Because XLS and XLSX are proprietary formats, you may need to install an extra package for this to work.  Pandas can work with the [openpyxl](https://pypi.org/project/openpyxl/) package to make Dataframes.

**Exercise**: Read the Excel file into Pandas again, using the `pd.read_excel(engine='openpyxl')` function.